services:
  wordpress:
    build:
      context: ./wordpress
      dockerfile: docker/Dockerfile
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    volumes:
      - ./wordpress/src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}.middlewares=security-headers@file,block-scan@file,compress@file,anubis@docker"
    networks:
      - web
      - backend

  db:
    image: mariadb:11.4
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Europe/Paris
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=false"
    networks:
      - backend

  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1 # Traefik needs to list containers
      SERVICES: 1 # Needed for Docker Swarm (safe to keep)
      NETWORKS: 1 # Needed to discover container networks
      TASKS: 1 # Needed for Docker Swarm tasks
      # Everything else defaults to 0 (denied)
      POST: 0 # Explicitly deny write operations
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket # Isolated network, NOT on 'web'

  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
      # - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375" # Point to the proxy instead of the socket
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Resolver
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Providers
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/acme.json:/letsencrypt/acme.json"
      - "./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
    networks:
      - web
      - socket

  anubis:
    image: ghcr.io/techarohq/anubis:main
    container_name: anubis
    environment:
      - BIND=:8080 # where to listen for Traefik
      - "TARGET= " # do redirect - ensure there is a space after '='
      # Specifies which domains Anubis is allowed to redirect to.
      - REDIRECT_DOMAINS=${DOMAIN_NAME}
      # Should be the full external URL for Anubis (including scheme)
      - PUBLIC_URL=https://${ANUBIS_DOMAIN_NAME}
      # Should match your domain for proper cookie scoping
      - COOKIE_DOMAIN=${DOMAIN_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anubis.rule=Host(`${ANUBIS_DOMAIN_NAME}`)" # Only Matching Requests for this domain
      - "traefik.http.routers.anubis.entrypoints=websecure"
      - "traefik.http.services.anubis.loadbalancer.server.port=8080" # telling Traefik where to receive requests
      - "traefik.http.routers.anubis.service=anubis" # telling Traefik to use the above specified port
      - "traefik.http.routers.anubis.tls.certresolver=myresolver" # telling Traefik to resolve a cert for Anubis
    networks:
      - web

volumes:
  db_data:

networks:
  backend:
    internal: true
  socket:
    internal: true
  web:
    driver: bridge
